export const projects = [
  {
    _id: "5f660fad647d75156db41cbe",
    projectId: "wOHkdr2e2",
    name: "Project1",
    demo: "https://p.appp.com",
    code: "https://op.app.com",
    type: "fullstack",
    description: "A full stack app",
    userId: "3SJTd1d-m",
    techstack: ["reactjs"],
    image: {
      _id: "5f660fad647d75156db41cbc",
      length: 33308,
      chunkSize: 261120,
      uploadDate: "2020-09-19T14:03:25.677Z",
      filename: "9939b663d514c8e58def218b7a68b74c",
      md5: "89ce7bd3d651b204b127b5468e1b211d",
      contentType: "image/png",
    },
    __v: 0,
  },
];
export const projectFilterCategory = [
  { name: "All", img: "icons8-workspace-one-128.png", disabled: true },
  { name: "ReactJS", img: "icons8-react-100.png", disabled: false },
  { name: "AngularJS", img: "icons8-angularjs-96.png", disabled: false },
  { name: "FullStack", img: "icons8-stack-correctly-96.png", disabled: false },
  { name: "Games", img: "icons8-games-folder-96.png", disabled: false },
  { name: "ML", img: "icons8-learning-96.png", disabled: false },
  { name: "NodeJS", img: "icons8-node-js-96.png", disabled: false },
  { name: "Clones", img: "header-icon.png", disabled: false },
  { name: "Html", img: "icons8-html-5-96.png", disabled: false },
  { name: "CSS", img: "icons8-css3-96.png", disabled: false },
  { name: "Javascript", img: "icons8-javascript-96.png", disabled: false },
  { name: "Typescript", img: "icons8-typescript-96.png", disabled: false },
];
